# Orb 'circleci/maven@0.0.12' resolved to 'circleci/maven@0.0.12'
version: 2
jobs:
  maven/test:
    docker:
    - image: circleci/openjdk:8-jdk-node
    steps:
    - checkout
    - setup_remote_docker
    - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker run --network
    - run:
        name: Generate Cache Checksum
        command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
    - restore_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - run:
        name: Install Dependencies
        command: mvn dependency:go-offline --settings 'pom.xml'
    - run:
        name: Run Tests
        command: mvn clean install -DPARALLEL=2 -DBROWSER=Chrome -DLOCAL=False
    - save_cache:
        paths:
        - ~/.m2
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - store_test_results:
        path: target/surefire-reports
workflows:
  maven_test:
    jobs:
    - maven/test
  version: 2

# Original config.yml file:
# version: 2.1
# 
# orbs:
#   maven: circleci/maven@0.0.12
# 
# workflows:
#   maven_test:
#     jobs:
#       - maven/test # checkout, build, test, and upload test results